---
- name: Upgrade GLIBC to version 2.34
  hosts: all
  become: true
  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Check current GLIBC version
      shell: ldd --version
      register: current_glibc
      changed_when: false

    - name: Check if upgrade is needed
      set_fact:
        upgrade_needed: "{{ glibc_version not in current_glibc.stdout_lines[0] }}"

    - name: Display current version
      debug:
        msg: "Current GLIBC version: {{ current_glibc.stdout_lines[0] }}"

    - name: Check system architecture
      fail:
        msg: "This playbook only supports x86_64 architecture"
      when: ansible_architecture != "x86_64"

  tasks:
    - name: Include backup tasks
      include_tasks: tasks/backup.yml
      when: upgrade_needed

    - name: Include preparation tasks
      include_tasks: tasks/prepare.yml
      when: upgrade_needed

    - name: Include upgrade tasks
      include_tasks: tasks/upgrade.yml
      when: upgrade_needed

    - name: Include verification tasks
      include_tasks: tasks/verify.yml
      when: upgrade_needed

  post_tasks:
    - name: Clean up build files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/usr/local/src/glibc-{{ glibc_version }}.tar.gz"
        - "/usr/local/src/glibc-{{ glibc_version }}"
        - "/usr/local/src/glibc-build"
      when: upgrade_needed

    - name: Final status message
      debug:
        msg: "GLIBC upgrade completed successfully. New version: {{ glibc_version }}"
      when: upgrade_needed

  handlers:
    - name: Reboot system
      reboot:
        msg: "Rebooting after GLIBC upgrade"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
      listen: "reboot_required"