---
- name: Install LetsEncrypt (Certbot) on Ubuntu 22.04
  hosts: all
  become: yes
  gather_facts: yes

  # Verify we're running on Ubuntu 22.04
  pre_tasks:
    - name: Check Ubuntu version
      fail:
        msg: "This playbook requires Ubuntu 22.04"
      when: ansible_distribution != 'Ubuntu' or ansible_distribution_version != '22.04'

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install software-properties-common
      apt:
        name: software-properties-common
        state: present

    - name: Add Certbot repository
      apt_repository:
        repo: ppa:certbot/certbot
        state: present

    - name: Install Certbot
      apt:
        name: 
          - certbot
          - python3-certbot
        state: present

    - name: Verify Certbot installation
      command: certbot --version
      register: certbot_version
      changed_when: false

    - name: Display Certbot version
      debug:
        var: certbot_version.stdout