apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-service
  name: postgres-service
spec:
  externalName: <RDS-Endpoint>
  selector:
    app: postgres-service
  type: ExternalName
status:
  loadBalancer: {}